import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { FileKindSchema, LanguageIdSchema, classifyFile, type ClassifyFileInput } from "../../src/cartographer";

const textHead = new TextEncoder().encode("export const value = 1;\n");

function inputFor(normalizedPath: string, headBuffer: Uint8Array = textHead): ClassifyFileInput {
  const segments = normalizedPath.split("/");
  const basename = segments[segments.length - 1] ?? normalizedPath;
  const extensionStart = basename.lastIndexOf(".");
  const extension = extensionStart >= 0 ? basename.slice(extensionStart + 1) : "";
  return { normalizedPath, basename, extension, headBuffer };
}

describe("Cartographer T3 file classifier", () => {
  it("classifies required source, test, config, doc, asset, lockfile, generated, and unknown cases", () => {
    // Given: representative file facts from the T3 acceptance list.
    const cases = [
      { path: "src/index.ts", expected: { kind: "source", language: "typescript" } },
      { path: "src/mod.mts", expected: { kind: "source", language: "typescript" } },
      { path: "src/util.cts", expected: { kind: "source", language: "typescript" } },
      { path: "app.test.ts", expected: { kind: "test", language: "typescript" } },
      { path: "tsconfig.json", expected: { kind: "config", language: "json" } },
      { path: "vitest.config.ts", expected: { kind: "config", language: "typescript" } },
      { path: "docs/architecture.md", expected: { kind: "doc", language: "markdown" } },
      { path: "logo.png", expected: { kind: "asset", language: "unknown" } },
      { path: "package-lock.json", expected: { kind: "lockfile", language: "json" } },
      { path: "foo.generated.ts", expected: { kind: "generated", language: "typescript" } },
      { path: "script.py", expected: { kind: "source", language: "unknown" } },
      { path: "data.xyz", expected: { kind: "unknown", language: "unknown" } },
      { path: ".env.example", expected: { kind: "config", language: "unknown" } },
    ] satisfies readonly { readonly path: string; readonly expected: ReturnType<typeof classifyFile> }[];

    // When: each path is classified from already-supplied metadata.
    const classified = cases.map((testCase) => ({ path: testCase.path, result: classifyFile(inputFor(testCase.path)) }));

    // Then: the classifier returns the exact T3 kind/language pairs.
    expect(classified).toEqual(cases.map((testCase) => ({ path: testCase.path, result: testCase.expected })));
  });

  it("classifies NUL-containing head buffers as binary after asset extensions", () => {
    // Given: file facts with binary-looking content and no asset extension.
    const binaryHead = new Uint8Array([65, 0, 66]);

    // When: the file is classified.
    const result = classifyFile(inputFor("src/blob.dat", binaryHead));

    // Then: the NUL byte drives the binary kind while the extension stays language-unknown.
    expect(result).toEqual({ kind: "binary", language: "unknown" });
  });

  it("preserves the T3 priority order for generated, test, fixture, config, doc, source, and vendor paths", () => {
    // Given: overlapping file facts where earlier T3 rules must win.
    const generatedHeader = new TextEncoder().encode("// This file was generated by a tool.\n");
    const cases = [
      { path: "package-lock.json", head: generatedHeader, expected: { kind: "lockfile", language: "json" } },
      { path: "image.png", head: new Uint8Array([0]), expected: { kind: "asset", language: "unknown" } },
      { path: "tests/fixture-data.ts", head: textHead, expected: { kind: "test", language: "typescript" } },
      { path: "fixtures/example.ts", head: textHead, expected: { kind: "fixture", language: "typescript" } },
      { path: "package.config.mjs", head: textHead, expected: { kind: "config", language: "javascript" } },
      { path: "workflows/build.yaml", head: textHead, expected: { kind: "config", language: "yaml" } },
      { path: "README.dev", head: textHead, expected: { kind: "doc", language: "unknown" } },
      { path: "vendor/manifest.lock", head: textHead, expected: { kind: "vendor", language: "unknown" } },
    ] satisfies readonly { readonly path: string; readonly head: Uint8Array; readonly expected: ReturnType<typeof classifyFile> }[];

    // When: overlapping facts are classified.
    const classified = cases.map((testCase) => ({ path: testCase.path, result: classifyFile(inputFor(testCase.path, testCase.head)) }));

    // Then: the first matching T3 rule determines the kind.
    expect(classified).toEqual(cases.map((testCase) => ({ path: testCase.path, result: testCase.expected })));
  });

  it("is total over random extension strings and returns only public union members", () => {
    // Given: arbitrary extension strings supplied as already-normalized scanner facts.
    const extensionArb = fc.string({ maxLength: 32 });

    // When: the classifier evaluates random extensions.
    fc.assert(
      fc.property(extensionArb, (extension) => {
        const normalizedPath = `random/file.${extension}`;
        const result = classifyFile({ normalizedPath, basename: `file.${extension}`, extension, headBuffer: textHead });

        // Then: every result is a valid stable Cartographer union value.
        return FileKindSchema.safeParse(result.kind).success && LanguageIdSchema.safeParse(result.language).success;
      }),
      { numRuns: 200 },
    );
  });
});
