import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import ignore from "ignore";
import { afterEach, describe, expect, it } from "vitest";
import {
  MAX_IGNORE_FILE_BYTES,
  loadIgnoreMatchers,
  shouldIgnoreFile,
  type IgnoreFileInput,
  type IgnoreMatcher,
} from "../../src/cartographer";

const emptyMatcher: IgnoreMatcher = ignore();

const textHead = new TextEncoder().encode("export const value = 1;\n");

const defaultInput = {
  normalizedPath: "src/a.ts",
  basename: "a.ts",
  isSymlink: false,
  isDirectory: false,
  sizeBytes: 128,
  headBuffer: textHead,
  gitignore: emptyMatcher,
  rectorignore: emptyMatcher,
  maxFileSizeBytes: 1024,
} satisfies IgnoreFileInput;

function decide(overrides: Partial<IgnoreFileInput> = {}) {
  return shouldIgnoreFile({ ...defaultInput, ...overrides });
}

describe("Cartographer T2 ignore policy", () => {
  const tempRoots: string[] = [];

  afterEach(async () => {
    await Promise.all(tempRoots.map((root) => fs.rm(root, { recursive: true, force: true })));
    tempRoots.length = 0;
  });

  async function makeRepo(): Promise<string> {
    const repoRoot = await fs.mkdtemp(path.join(tmpdir(), "rector-ignore-policy-"));
    tempRoots.push(repoRoot);
    return repoRoot;
  }

  it("applies symlink, built-in, and env decisions before content-driven rules", () => {
    // Given: path metadata that should be decided without file content.
    const envDecision = decide({ normalizedPath: ".env.production", basename: ".env.production", headBuffer: undefined });
    const envExampleDecision = decide({ normalizedPath: ".env.example", basename: ".env.example", headBuffer: undefined });

    // When: high-priority policy rules are evaluated.
    const symlinkDecision = decide({ isSymlink: true });
    const builtInDirDecision = decide({ normalizedPath: "node_modules/pkg/index.js", basename: "index.js" });
    const builtInFileDecision = decide({ normalizedPath: ".git/HEAD", basename: "HEAD" });
    const builtInBasenameDecision = decide({ normalizedPath: "src/.DS_Store", basename: ".DS_Store" });

    // Then: exact sources and reasons expose the first matching rule.
    expect(symlinkDecision).toEqual({ ignored: true, reason: "symlink not followed", source: "symlink" });
    expect(builtInDirDecision.source).toBe("built_in");
    expect(builtInFileDecision.source).toBe("built_in");
    expect(builtInBasenameDecision.source).toBe("built_in");
    expect(envDecision).toMatchObject({ ignored: true, source: "env" });
    expect(envDecision.reason).toContain("never read");
    expect(envExampleDecision).toEqual({ ignored: false, source: "none" });
  });

  it("respects gitignore before rectorignore and supports trailing slash directory patterns", () => {
    // Given: root ignore matchers with overlapping file and directory rules.
    const gitignore = ignore().add(["*.log", "logs-dir/"]);
    const rectorignore = ignore().add(["*.log", "secrets/**"]);

    // When: file and directory decisions are evaluated.
    const gitignoreDecision = decide({ normalizedPath: "logs/app.log", basename: "app.log", gitignore, rectorignore });
    const rectorignoreDecision = decide({ normalizedPath: "secrets/token.txt", basename: "token.txt", gitignore, rectorignore });
    const directoryDecision = decide({ normalizedPath: "logs-dir", basename: "logs-dir", isDirectory: true, gitignore, rectorignore });

    // Then: .gitignore wins overlap, .rectorignore fills gaps, and directory slash queries work.
    expect(gitignoreDecision.source).toBe("gitignore");
    expect(rectorignoreDecision.source).toBe("rectorignore");
    expect(directoryDecision.source).toBe("gitignore");
  });

  it("applies size, binary, generated, lockfile, and normal-file decisions", () => {
    // Given: bounded file facts supplied by the future scanner.
    const binaryHead = new Uint8Array([65, 0, 66]);
    const generatedHead = new TextEncoder().encode("// Code generated by tool. DO NOT EDIT.\n");

    // When: lower-priority content and metadata rules are evaluated.
    const sizeDecision = decide({ sizeBytes: 1025 });
    const binaryDecision = decide({ normalizedPath: "assets/blob.bin", basename: "blob.bin", headBuffer: binaryHead });
    const generatedFilenameDecision = decide({ normalizedPath: "src/foo.generated.ts", basename: "foo.generated.ts" });
    const generatedHeaderDecision = decide({ normalizedPath: "src/api.ts", basename: "api.ts", headBuffer: generatedHead });
    const lockfileDecision = decide({ normalizedPath: "package-lock.json", basename: "package-lock.json", headBuffer: generatedHead });
    const normalDecision = decide();

    // Then: each rule reports the exact T2 source and lockfiles remain indexable.
    expect(sizeDecision.source).toBe("size_limit");
    expect(binaryDecision.source).toBe("binary");
    expect(generatedFilenameDecision.source).toBe("generated");
    expect(generatedHeaderDecision.source).toBe("generated");
    expect(lockfileDecision).toEqual({ ignored: false, source: "none" });
    expect(normalDecision).toEqual({ ignored: false, source: "none" });
  });

  it("loads absent rectorignore as a no-op matcher", async () => {
    // Given: a repo with only a root .gitignore file.
    const repoRoot = await makeRepo();
    await fs.writeFile(path.join(repoRoot, ".gitignore"), "*.log\n", "utf8");

    // When: root matchers are loaded.
    const result = await loadIgnoreMatchers(repoRoot);
    const normalDecision = decide({ gitignore: result.gitignore, rectorignore: result.rectorignore });
    const gitignoreDecision = decide({ normalizedPath: "debug.log", basename: "debug.log", gitignore: result.gitignore, rectorignore: result.rectorignore });

    // Then: missing .rectorignore is not an error and ignores nothing.
    expect(result.errors).toEqual([]);
    expect(normalDecision).toEqual({ ignored: false, source: "none" });
    expect(gitignoreDecision.source).toBe("gitignore");
  });

  it("treats oversized root gitignore as absent with a recoverable read error", async () => {
    // Given: a root .gitignore larger than the hard cap.
    const repoRoot = await makeRepo();
    await fs.writeFile(path.join(repoRoot, ".gitignore"), `${"x".repeat(MAX_IGNORE_FILE_BYTES + 1)}\n*.log\n`, "utf8");

    // When: root matchers are loaded.
    const result = await loadIgnoreMatchers(repoRoot);
    const decision = decide({ normalizedPath: "debug.log", basename: "debug.log", gitignore: result.gitignore, rectorignore: result.rectorignore });

    // Then: the oversized config is recoverable and its patterns are not applied.
    expect(decision).toEqual({ ignored: false, source: "none" });
    expect(result.errors).toEqual([
      {
        path: ".gitignore",
        stage: "read",
        message: `.gitignore exceeds ${MAX_IGNORE_FILE_BYTES} bytes`,
        recoverable: true,
      },
    ]);
  });
});
