import type { Dirent, Stats } from "node:fs";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import type { CartographerScanEmitter, CartographerScanEvent, FileNode, FileReader, RepoSnapshot, ScanResult } from "../../src/cartographer";
import { defaultFileReader } from "../../src/cartographer/repoScanner";

export const fixedNow = new Date("2026-06-20T00:00:00.000Z");
export const tempRoots: string[] = [];

export type FileReadCall = { readonly normalizedPath: string; readonly maxBytes?: number };
export type ScanEventLabel = { readonly type: CartographerScanEvent["type"]; readonly path: string };

type ReaderMethod = "lstat" | "readdir" | "readHead" | "readAll";
type ReaderFailure = { readonly method: ReaderMethod; readonly normalizedPath: string; readonly message: string };
type StableFileNode = Omit<FileNode, "lastIndexedAt">;
type StableRepoSnapshot = Omit<RepoSnapshot, "createdAt">;
type StableScanResult = Omit<ScanResult, "files" | "changedFiles" | "snapshot"> & {
  readonly snapshot: StableRepoSnapshot;
  readonly files: readonly StableFileNode[];
  readonly changedFiles: readonly StableFileNode[];
};

export function stripVolatile(result: ScanResult): StableScanResult {
  const { createdAt: _createdAt, ...snapshot } = result.snapshot;
  return {
    ...result,
    snapshot,
    files: result.files.map(stripFileVolatile),
    changedFiles: result.changedFiles.map(stripFileVolatile),
  };
}

export function isSortedUtf16(values: readonly string[]): boolean {
  return values.every((value, index) => index === 0 || compareUtf16(values[index - 1] ?? "", value) <= 0);
}

export async function makeFixtureRepo(): Promise<string> {
  const repoRoot = await fs.mkdtemp(path.join(tmpdir(), "rector-repo-scanner-"));
  tempRoots.push(repoRoot);
  await writeFixtureFile(repoRoot, "package.json", "{\"name\":\"fixture\"}\n");
  await writeFixtureFile(repoRoot, "tsconfig.json", "{\"compilerOptions\":{}}\n");
  await writeFixtureFile(repoRoot, "src/index.ts", "export const indexValue = 1;\n");
  await writeFixtureFile(repoRoot, "src/app.ts", "export const appValue = 2;\n");
  await writeFixtureFile(repoRoot, "src/app.test.ts", "import './app';\n");
  await writeFixtureFile(repoRoot, "docs/architecture.md", "# Architecture\n");
  await writeFixtureFile(repoRoot, "node_modules/ignored/index.js", "module.exports = 1;\n");
  await writeFixtureFile(repoRoot, "dist/generated.js", "// Code generated by build\n");
  await writeFixtureFile(repoRoot, ".env.production", "SECRET=value\n");
  await writeFixtureFile(repoRoot, ".env.example", "EXAMPLE=value\n");
  await writeFixtureFile(repoRoot, ".gitignore", "ignored-by-git.txt\n");
  await writeFixtureFile(repoRoot, ".rectorignore", "ignored-by-rector.txt\n");
  await writeFixtureFile(repoRoot, ".git/HEAD", "ref: refs/heads/main\n");
  await fs.symlink(path.join(repoRoot, "src", "index.ts"), path.join(repoRoot, "linked-index.ts"));
  return repoRoot;
}

export function makeSpyingReader(repoRoot: string, failures: readonly ReaderFailure[] = []): { readonly reader: FileReader; readonly headCalls: readonly FileReadCall[]; readonly allCalls: readonly FileReadCall[] } {
  const headCalls: FileReadCall[] = [];
  const allCalls: FileReadCall[] = [];
  const failureFor = (method: ReaderMethod, absolutePath: string): ReaderFailure | undefined =>
    failures.find((failure) => failure.method === method && failure.normalizedPath === normalizedFromRoot(repoRoot, absolutePath));
  const reader: FileReader = {
    async lstat(absolutePath: string): Promise<Stats> {
      const failure = failureFor("lstat", absolutePath);
      if (failure !== undefined) {
        throw new Error(failure.message);
      }
      return defaultFileReader.lstat(absolutePath);
    },
    async readdir(absolutePath: string): Promise<readonly Dirent[]> {
      const failure = failureFor("readdir", absolutePath);
      if (failure !== undefined) {
        throw new Error(failure.message);
      }
      return defaultFileReader.readdir(absolutePath);
    },
    async readHead(absolutePath: string, maxBytes: number): Promise<Uint8Array> {
      const failure = failureFor("readHead", absolutePath);
      if (failure !== undefined) {
        throw new Error(failure.message);
      }
      headCalls.push({ normalizedPath: normalizedFromRoot(repoRoot, absolutePath), maxBytes });
      return defaultFileReader.readHead(absolutePath, maxBytes);
    },
    async readAll(absolutePath: string): Promise<Uint8Array> {
      const failure = failureFor("readAll", absolutePath);
      if (failure !== undefined) {
        throw new Error(failure.message);
      }
      allCalls.push({ normalizedPath: normalizedFromRoot(repoRoot, absolutePath) });
      return defaultFileReader.readAll(absolutePath);
    },
  };
  return { reader, headCalls, allCalls };
}

export function labelForEvent(event: CartographerScanEvent): ScanEventLabel {
  switch (event.type) {
    case "CARTOGRAPHER_SCAN_STARTED":
      return { type: event.type, path: event.repoRoot };
    case "CARTOGRAPHER_FILE_INDEXED":
    case "CARTOGRAPHER_FILE_DELETED":
      return { type: event.type, path: event.path };
    case "CARTOGRAPHER_FILE_IGNORED":
      return { type: event.type, path: event.ignoredFile.path };
    case "CARTOGRAPHER_SCAN_COMPLETED":
      return { type: event.type, path: event.summary.repoRoot };
    case "CARTOGRAPHER_SCAN_FAILED":
      return { type: event.type, path: event.error.path };
    default: {
      const unreachable: never = event;
      return unreachable;
    }
  }
}

export function collectEvents(): { readonly events: readonly CartographerScanEvent[]; readonly emitter: CartographerScanEmitter } {
  const events: CartographerScanEvent[] = [];
  return {
    events,
    emitter: (event) => {
      events.push(event);
    },
  };
}

function stripFileVolatile(file: FileNode): StableFileNode {
  const { lastIndexedAt: _lastIndexedAt, ...stableFile } = file;
  return stableFile;
}

function compareUtf16(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

async function writeFixtureFile(repoRoot: string, normalizedPath: string, contents: string): Promise<void> {
  const absolutePath = path.join(repoRoot, ...normalizedPath.split("/"));
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });
  await fs.writeFile(absolutePath, contents, "utf8");
}

function normalizedFromRoot(repoRoot: string, absolutePath: string): string {
  const relativePath = path.relative(repoRoot, absolutePath);
  return relativePath === "" ? "." : relativePath.split(path.sep).join("/").replace(/\\/g, "/");
}
