import type { ClassifyFileInput, FileKind, LanguageId } from "./types";

const LOCKFILE_BASENAMES = new Set(["package-lock.json", "pnpm-lock.yaml", "yarn.lock"]);
const ASSET_EXTENSIONS = new Set([
  "png",
  "jpg",
  "jpeg",
  "gif",
  "svg",
  "ico",
  "pdf",
  "zip",
  "tar",
  "gz",
  "tgz",
  "woff",
  "woff2",
  "ttf",
  "eot",
  "mp4",
  "mov",
  "mp3",
  "wasm",
  "webp",
  "bmp",
]);
const SOURCE_EXTENSIONS = new Set(["ts", "tsx", "js", "jsx", "mjs", "cjs", "mts", "cts", "py", "go", "rs", "java", "kt"]);
const TEST_SEGMENTS = new Set(["__tests__", "tests", "test"]);
const FIXTURE_SEGMENTS = new Set(["fixtures", "__fixtures__", "examples", "samples"]);
const GENERATED_NAME_PATTERNS = [/\.generated\./, /(^|\/)generated\//];
const GENERATED_HEAD_MARKERS = ["Code generated by", "@generated", "<auto-generated", "This file was generated"];

export function classifyFile(input: ClassifyFileInput): { readonly kind: FileKind; readonly language: LanguageId } {
  const extension = normalizeExtension(input.extension);
  const language = classifyLanguage(extension);
  const segments = input.normalizedPath.split("/");

  if (LOCKFILE_BASENAMES.has(input.basename)) {
    return { kind: "lockfile", language };
  }
  if (ASSET_EXTENSIONS.has(extension)) {
    return { kind: "asset", language };
  }
  if (hasNulByte(input.headBuffer)) {
    return { kind: "binary", language };
  }
  if (isGeneratedFile(input.normalizedPath, input.headBuffer)) {
    return { kind: "generated", language };
  }
  if (isTestFile(input.basename, segments)) {
    return { kind: "test", language };
  }
  if (hasSegment(segments, FIXTURE_SEGMENTS)) {
    return { kind: "fixture", language };
  }
  if (isConfigFile(input.normalizedPath, input.basename, extension, segments.length)) {
    return { kind: "config", language };
  }
  if (isDocFile(input.basename, extension, segments)) {
    return { kind: "doc", language };
  }
  if (SOURCE_EXTENSIONS.has(extension)) {
    return { kind: "source", language };
  }
  if (segments.includes("vendor")) {
    return { kind: "vendor", language };
  }
  return { kind: "unknown", language };
}

function normalizeExtension(extension: string): string {
  return extension.toLowerCase().replace(/^\.+/, "");
}

function classifyLanguage(extension: string): LanguageId {
  switch (extension) {
    case "ts":
    case "tsx":
    case "mts":
    case "cts":
      return "typescript";
    case "js":
    case "jsx":
    case "mjs":
    case "cjs":
      return "javascript";
    case "json":
      return "json";
    case "md":
    case "mdx":
      return "markdown";
    case "yml":
    case "yaml":
      return "yaml";
    case "css":
      return "css";
    case "html":
    case "htm":
      return "html";
    case "sh":
    case "bash":
      return "shell";
    case "txt":
      return "text";
    default:
      return "unknown";
  }
}

function hasNulByte(headBuffer: Uint8Array | undefined): boolean {
  return headBuffer?.some((byte) => byte === 0) === true;
}

function isGeneratedFile(normalizedPath: string, headBuffer: Uint8Array | undefined): boolean {
  return GENERATED_NAME_PATTERNS.some((pattern) => pattern.test(normalizedPath)) || isGeneratedHead(headBuffer);
}

function isGeneratedHead(headBuffer: Uint8Array | undefined): boolean {
  if (headBuffer === undefined) {
    return false;
  }
  const text = new TextDecoder().decode(headBuffer);
  return GENERATED_HEAD_MARKERS.some((marker) => text.includes(marker));
}

function isTestFile(basename: string, segments: readonly string[]): boolean {
  return /\.(test|spec)\./.test(basename) || hasSegment(segments, TEST_SEGMENTS);
}

function hasSegment(segments: readonly string[], allowed: ReadonlySet<string>): boolean {
  return segments.some((segment) => allowed.has(segment));
}

function isConfigFile(normalizedPath: string, basename: string, extension: string, segmentCount: number): boolean {
  return (
    basename === "package.json" ||
    /^tsconfig.*\.json$/.test(basename) ||
    /^(vite|vitest|eslint)\.config\./.test(basename) ||
    /^\.prettierrc/.test(basename) ||
    basename === ".env.example" ||
    /\.config\.(js|ts|mjs|cjs)$/.test(basename) ||
    ((extension === "yml" || extension === "yaml") && segmentCount <= 2 && !normalizedPath.startsWith("docs/"))
  );
}

function isDocFile(basename: string, extension: string, segments: readonly string[]): boolean {
  return extension === "md" || extension === "mdx" || basename.startsWith("README") || basename === "AGENTS.md" || segments.includes("docs");
}
