import { promises as fs } from "node:fs";
import path from "node:path";
import ignore from "ignore";
import type { IgnoreDecision, IgnoreFileInput, IgnoreMatcher, LoadIgnoreMatchersResult, ScanError } from "./types";

export const MAX_IGNORE_FILE_BYTES = 256 * 1024;

const BUILT_IN_SEGMENTS = new Set([
  ".git",
  "node_modules",
  "dist",
  "build",
  "coverage",
  ".next",
  ".turbo",
  ".cache",
  "out",
  "tmp",
  "temp",
  ".worktrees",
  ".omo",
]);
const BUILT_IN_BASENAMES = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);
const LOCKFILE_BASENAMES = new Set(["package-lock.json", "pnpm-lock.yaml", "yarn.lock"]);
const GENERATED_NAME_PATTERNS = [/\.generated\./, /(^|\/)generated\//];
const GENERATED_HEAD_MARKERS = ["Code generated by", "@generated", "<auto-generated", "This file was generated"];
const IGNORE_CONFIG_FILES = [".gitignore", ".rectorignore"] as const;

type IgnoreConfigFile = (typeof IGNORE_CONFIG_FILES)[number];

export function shouldIgnoreFile(input: IgnoreFileInput): IgnoreDecision {
  if (input.isSymlink) {
    return { ignored: true, reason: "symlink not followed", source: "symlink" };
  }
  if (isBuiltInPath(input.normalizedPath, input.basename)) {
    return { ignored: true, reason: "built-in ignore", source: "built_in" };
  }
  if (isEnvBasename(input.basename)) {
    return { ignored: true, reason: "env file (never read)", source: "env" };
  }
  if (matchesMatcher(input.gitignore, input.normalizedPath, input.isDirectory)) {
    return { ignored: true, reason: "matched .gitignore", source: "gitignore" };
  }
  if (matchesMatcher(input.rectorignore, input.normalizedPath, input.isDirectory)) {
    return { ignored: true, reason: "matched .rectorignore", source: "rectorignore" };
  }
  if (input.sizeBytes > input.maxFileSizeBytes) {
    return { ignored: true, reason: `file exceeds ${input.maxFileSizeBytes} bytes`, source: "size_limit" };
  }
  if (isBinaryHead(input.headBuffer)) {
    return { ignored: true, reason: "binary file", source: "binary" };
  }
  if (isGeneratedFile(input.normalizedPath, input.basename, input.headBuffer)) {
    return { ignored: true, reason: "generated file", source: "generated" };
  }
  return { ignored: false, source: "none" };
}

export async function loadIgnoreMatchers(repoRoot: string): Promise<LoadIgnoreMatchersResult> {
  const results = await Promise.all(IGNORE_CONFIG_FILES.map((file) => readIgnoreConfig(repoRoot, file)));
  const errors = results.flatMap((result) => result.errors);

  return {
    gitignore: results[0].matcher,
    rectorignore: results[1].matcher,
    errors,
  };
}

function isBuiltInPath(normalizedPath: string, basename: string): boolean {
  return BUILT_IN_BASENAMES.has(basename) || normalizedPath.split("/").some((segment) => BUILT_IN_SEGMENTS.has(segment));
}

function isEnvBasename(basename: string): boolean {
  return basename !== ".env.example" && /^\.env(\..+)?$/.test(basename);
}

function matchesMatcher(matcher: IgnoreMatcher, normalizedPath: string, isDirectory: boolean): boolean {
  return matcher.ignores(normalizedPath) || (isDirectory && matcher.ignores(`${normalizedPath}/`));
}

function isBinaryHead(headBuffer: Uint8Array | undefined): boolean {
  return headBuffer?.some((byte) => byte === 0) === true;
}

function isGeneratedFile(normalizedPath: string, basename: string, headBuffer: Uint8Array | undefined): boolean {
  if (LOCKFILE_BASENAMES.has(basename)) {
    return false;
  }
  return GENERATED_NAME_PATTERNS.some((pattern) => pattern.test(normalizedPath)) || isGeneratedHead(headBuffer);
}

function isGeneratedHead(headBuffer: Uint8Array | undefined): boolean {
  if (headBuffer === undefined) {
    return false;
  }
  const text = new TextDecoder().decode(headBuffer);
  return GENERATED_HEAD_MARKERS.some((marker) => text.includes(marker));
}

async function readIgnoreConfig(repoRoot: string, file: IgnoreConfigFile): Promise<{ readonly matcher: IgnoreMatcher; readonly errors: readonly ScanError[] }> {
  const configPath = path.join(repoRoot, file);
  const statResult = await statIgnoreConfig(configPath, file);
  if (!statResult.exists) {
    return { matcher: ignore(), errors: [] };
  }
  if (statResult.error !== undefined) {
    return statResult.error.recoverable ? { matcher: ignore(), errors: [statResult.error] } : { matcher: ignore(), errors: [] };
  }
  if (statResult.sizeBytes > MAX_IGNORE_FILE_BYTES) {
    return { matcher: ignore(), errors: [readError(file, `${file} exceeds ${MAX_IGNORE_FILE_BYTES} bytes`)] };
  }
  try {
    return { matcher: ignore().add(await fs.readFile(configPath, "utf8")), errors: [] };
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown read failure";
    return { matcher: ignore(), errors: [readError(file, message)] };
  }
}

async function statIgnoreConfig(
  configPath: string,
  file: IgnoreConfigFile,
): Promise<{ readonly exists: boolean; readonly sizeBytes: number; readonly error?: ScanError }> {
  try {
    const stat = await fs.stat(configPath);
    return { exists: true, sizeBytes: stat.size };
  } catch (error) {
    if (getErrorCode(error) === "ENOENT") {
      return { exists: false, sizeBytes: 0 };
    }
    const message = error instanceof Error ? error.message : "unknown stat failure";
    return { exists: true, sizeBytes: 0, error: readError(file, message) };
  }
}

function getErrorCode(error: unknown): string | undefined {
  if (typeof error !== "object" || error === null || !("code" in error)) {
    return undefined;
  }
  const code = error.code;
  return typeof code === "string" ? code : undefined;
}

function readError(file: IgnoreConfigFile, message: string): ScanError {
  return { path: file, stage: "read", message, recoverable: true };
}
